apiVersion: apps/v1
kind: Deployment
metadata:
  name: e-shop-web
  labels:
    app: e-shop-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: e-shop-web
  template:
    metadata:
      name: e-shop-web
      labels:
        app: e-shop-web
    spec:
      containers:
        - name: e-shop-web
          image: e-shop-web:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
      restartPolicy: Always
      