apiVersion: apps/v1
kind: Deployment
metadata:
  name: e-shop-web
  labels:
    app: e-shop-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: e-shop-web
  template:
    metadata:
      name: e-shop-web
      labels:
        app: e-shop-web
    spec:
      containers:
        - name: e-shop-web
          image: ghcr.io/rayyau999/my-eshop-app:${WEB_TAG}
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              protocol: TCP
      restartPolicy: Always
      